import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/layout/Navbar'
import Footer from '@/components/layout/Footer'
import { SupabaseProvider } from '@/providers/SupabaseProvider'
import { CartProvider } from '@/providers/CartProvider'
import { ToasterProvider } from '@/providers/ToasterProvider'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = 'force-dynamic'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SupabaseProvider>
          <ToasterProvider>
            <CartProvider>
              <Navbar />
              <main className="min-h-[70vh]">{children}</main>
              <Footer />
            </CartProvider>
          </ToasterProvider>
        </SupabaseProvider>
      </body>
    </html>
  )
}
